#!/bin/bash
rcfile=$(head -n 1 .bclrc)
if [ $rcfile == "pink" ]; then 
  echo -en "\e[95;1;107m"
  echo "                      _           _                     "
  echo "                     / \_______ /|_\                    "
  echo "                    /          /_/ \__                  "
  echo "                   /             \_/ /                  "
  echo "                 _|_              |/|_                  "
  echo "                 _|_  O    _    O  _|_                  "
  echo "                 _|_      (_)      _|_                  "
  echo "                  \                 /                   "
  echo "                   _\_____________/_                    "
  echo "                  /  \/  (___)  \/  \                   "
  echo "                  \__(  o     o  )__/                   "
  echo -en "\e[31m"
  echo "                                                        "
  echo "             B E T T E R C A P  L O A D E R             "
  echo -en "\e[34;1m\e[5m"
  echo "                                                        "
  echo "                Copyright 2019 Thugcrowd                "
  echo -en "\e[0m\e[30;1;107m"
  echo "                                                        "
  echo "                          v0.3                          "
  echo -e "\e[0m"
  else
    echo -e "\e[32;1m"
    echo "   ______________     ______      ___  ________          "
    echo " .╲╲   _    _   ╱----╱     ╱_____╱   ╲╲╲.     ╱_         "
    echo "    )__╱    ╱___╲  _╱     ╱╱    ╱    ╱╱    ╱___(__       "
    echo "      ╱    ╱╱      ╲     ╱╱    ╱    ╱╱    ╱_╲     ╲      "
    echo "     ╱_____╲       ╱_____╲ _________╲ _______      ╲     "
    echo "    ╱╱╱╱╱╱╱╱╲_____╱╱╱╱╱╱╱╲╲╱╱╱╱╱╱╱╱╱╲╲╱╱╱╱╱╱╱╲_____╱╱.   "
    echo "  _________  ___________ ________ _______     ________   "
    echo " _)       ╱_.)   ._    ╱╱  ___  ╱╱      ╱_____╲____  (   "
    echo " ╲    |__╱  ╲__  |╱  _╱╱     ╱  ╱      ╱      X0  ╱   ╲  "
    echo "  ╲   :       ╱  ╱    ╲__   ╱  ╱╱_    ╱╲     ╱.  ╱     ╲ "
    echo " .╲╲___      ╱___╲      ╱_____╱╱╱╱____╱╲     ╲╲__      ╱ "
    echo "   ╱╱╱╱╲____╱╱╱╱╱╱╲____╱╱╱╱╱╱╱  ╱╱╱╱╱╱╱╱╲____╱╱╱╱╲____╱╱."
    echo "       ╱╱╱╱╱      ╱╱╱╱╱                 ╱╱╱╱╱    ╱╱╱╱╱   "
    echo -e "\e[0m\e[31m"
    echo "             B E T T E R C A P  L O A D E R             "
    echo -e "\e[36;1m\e[5m"
    echo "                Copyright 2019 Thugcrowd"
    echo -e "\e[0m\e[32;1m"
    echo "                          v0.3"
    echo -e "\e[0m"
fi 

bettercap $@
